spring.application.name=Day 6
spring.datasource.url=jdbc:mysql://localhost:3306/BillItemManagement
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update